### ISSUE TITLE
Drop browser ID code

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2861] opened 2017-06-23 19:40 UTC
We should remove the code that sets a unique cookie per-browser.  It interferes with caching and I don't believe it's very useful anymore.  My understanding is that it was created for two reasons:

 - Have a way to track editing sessions for non-logged-in users.  However, we don't allow this anymore
 - Prevent the editor from being open in 2 browsers at once by the same user.  However, it doesn't stop the user from opening it in 2 different tabs, so I don't think this accomplishes much.

**Comment by bendk** [comment] 2017-06-23 19:46
Implemented in the caching branch.

**Comment by PCF-Testing** [comment] 2017-07-01 15:23
A couple of issues that cropped up instantly:

- If one user is editing subtitles, for another user attempt to edit the same subtitle set silently fails. There is no error message explaining why the subtitles cannot be edited.

- Subtitles edited by the same user in multiple tabs of the same browser and different browsers behave in a different way. If subtitles are opened for editing in another browser tab, the editor announces that an unsaved copy of subtitles exists (in local storage) and prompts to restore the unsaved copy. However, if the user opens in a different browser, it is not even aware that an unsaved version exists in another browser. This can potentially lead to saving poorer subtitle versions and losing work - or part of it.

- If User A's editing session timed out and User B started editing subtitles, User A still can resume editing from the editor and 2 users will be editing simultaneously.

**Comment by bendk** [comment] 2017-07-06 19:25
> If one user is editing subtitles, for another user attempt to edit the same subtitle set silently fails. There is no error message explaining why the subtitles cannot be edited.

I tried this and got the normal error "Sorry, you cannot edit these subtitles now because they are being edited by another user. Please check back later."  Can you post the steps you took?  There's a lot of different ways to enter the editor.

> Subtitles edited by the same user in multiple tabs of the same browser and different browsers behave in a different way. If subtitles are opened for editing in another browser tab, the editor announces that an unsaved copy of subtitles exists (in local storage) and prompts to restore the unsaved copy. However, if the user opens in a different browser, it is not even aware that an unsaved version exists in another browser. This can potentially lead to saving poorer subtitle versions and losing work - or part of it.

I don't really understand this one.  It doesn't seem to be tied to this change, is there a regression here?  Also, I'm not sure what we can do in this situation, since if you open the subtitles with a different browser, then we can't access the local storage of the first browser.

> If User A's editing session timed out and User B started editing subtitles, User A still can resume editing from the editor and 2 users will be editing simultaneously.

I see what you mean, I believe that happens because we don't try to regain the lock in certain cases, like when I use re-open tab.  Is this a regression?  I think the same would happen with our current code.

**Comment by PCF-Testing** [comment] 2017-07-08 11:54
> I tried this and got the normal error "Sorry, you cannot edit these subtitles now because they are being edited by another user. Please check back later." Can you post the steps you took? There's a lot of different ways to enter the editor.

1. In Browser A, I sign in as User 1 and open subtitles for a certain public video for editing.
2. In Browser B, I sign in as User B and attempt to open the same subtitles for editing (does not matter which way, could be through "Edit Subtitles" button on the subtitle page or through "Improve These Subtitles" item in the embedder). This attempt is silently rejected, the editor would not open, but there is no error message - perhaps due to the issue described in https://github.com/pculture/amara-enterprise/issues/1433 (banner messages).

>  don't really understand this one. It doesn't seem to be tied to this change, is there a regression here?

Yes, it is a regression. Currently on production, if a user is editing subtitles in a browser and attempts to edit the same subtitles in another browser without closing that other session, the attempt is rejected with "Sorry, you cannot edit these subtitles now because they are being edited by another user. Please check back later." message.

> I see what you mean, I believe that happens because we don't try to regain the lock in certain cases, like when I use re-open tab. Is this a regression? I think the same would happen with our current code.

It is a regression. In our current code, User A will not be allowed to resume the timed out session if someone else started working on the subtitles.

**Comment by PCF-Testing** [comment] 2017-07-08 13:38
"This attempt is silently rejected, the editor would not open, but there is no error message"

Actually I spotted the missing error message later, in the same browser, but on a different user session, with a different test instance and on unisubs.example.com:8000 (rather than 9000).

**Comment by bendk** [comment] 2017-07-11 14:26
So the first case looks like it's just the issue about banner messages.  Let's work in #1433 for that one.

I think I understand the second case issue now, you're pointing out that there is a difference between allowing users to open the editor in multiple browsers and multiple tabs: in the multiple tabs case the browser saves the in-progress subtitles from the first session and in the second session, the user can resume them.  That's definitely true and I don't see any way around it, so we just need to decide if we can live with that.  It seems to me that there's enough other issues with opening the editor twice, regardless of whether it's two tabs or two browsers, that we can ignore this one.  Not sure what others think though.

I'm still confused about the last one, can you give exact instructions to reproduce it?  I've tried a bunch of ways without success.  Even the reopen tab method, which was by previous method isn't working anymore.

**Comment by PCF-Testing** [comment] 2017-07-18 10:35
OK, the issue with the banner is gone now - after updating the Varnish code, a second user trying to edit subtitles sees the correct error message explaining why access cannot be granted.

The problem with reclaiming the expiring sessions is still there though. For me. it is very consistent and easy to reproduce:

1. In Browser A, sign in as User 1 and open subtitles for a certain public video for editing.
2. Leave the subtitles and the editor untouched (no keystrokes, no mouse movements. You can switch to another browser or tab while leaving the editor open) for 15+ minutes. Once that time elapses, the editor will display a message about the session having timed out ("Your session has ended. You can try to resume, or close the editor.").
3. After the session in Browser A times out, sign in as User 2 In Browser B and open the same subtitles for editing (e.g. through "Edit Subtitles" button on the subtitle page). 
4. In browser A, click Try to Resume Work (this is only supposed to resume the timed out session if nobody else is editing these subtitles). The session resumes. Type something and save a draft.
5. Type something in Browser B and save a draft.
Result: both users can edit the same subtitles concurrently and save different subtitle versions in turn.

**Comment by bendk** [comment] 2017-07-20 15:16
Thanks for those steps to reproduce.  I was able to cause it to happen, but I was also able to cause it from staging.  I made #2885 for that issue and fixed it in a separate branch since I'm not sure how soon we will merge this one and I wanted to fix that issue immediately.

That said, I think all the issues are fixed, is there anything remaining?

**Comment by PCF-Testing** [comment] 2017-07-22 16:54
No, I think that was all I've found.

But maybe it would be better to keep this ticket and enterprise-1433 separately from 2848 and 2885, because the latter two are needed soon. Suppose we merge and deploy 2848 and 2885 first, and then go ahead with the caching branch?

**Comment by PCF-Testing** [comment] 2017-08-11 07:57
Deployed.

**Closed by PCF-Testing** 2017-08-11 07:57 UTC
