### ISSUE TITLE
Broken title template in subtitles view

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3330] opened 2018-08-09 17:20 UTC
https://github.com/pculture/unisubs/blob/3c9fa8760607cc7fca90431452c68fb9d2a217e3/templates/future/videos/subtitles.html#L19

The is.rtl conditional in the subtitles.html template is outside any tag, as well as the closing greater-than. It outputs the gt character when the conditional after h2 is true, and the literal text class="is-rtl" as well when the language being viewed is rtl.

```
<h2>{% if subtitle_version and subtitle_language and subtitle_language.get_title %}
            {% if subtitle_language.is_rtl %} class="is-rtl"{% endif %}>
            <bdi>{{ subtitle_language.title_display }}</bdi>
          {% else %}
            {{video.title_display}}
{% endif %}
```

**Comment by PCF-Testing** [comment] 2018-08-10 07:41
Duplicate of https://github.com/pculture/amara-enterprise/issues/2049.

**Closed by PCF-Testing** 2018-08-10 07:41 UTC
Labels: bug, type: bite-sized
