### ISSUE TITLE
Feature Request: press enter to edit subs in the Review dialog

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#251] opened 2013-07-11 07:11 UTC
When you're reviewing subtitles and notice a typo, you need to click the subtitle to start editing it.  Then you fix the typo and press enter to "save" it.

Pressing enter when you're not editing a subtitle does nothing, so maybe we could make it put the current subtitle in "editing" mode (and pause the video if it's playing)?  That way when you notice a typo you can just hit enter, fix typo, enter, and space or tab to start playing again.

**Comment by kslottow** [comment] 2016-10-28 17:04
@nslottow confirmed that this is the current functionality: "Enter" does nothing if you are not currently editing a subtitle.

**Comment by kslottow** [comment] 2016-11-01 21:10
@bendk @PCF-Testing Hi Ben and Maggie, just want to let you know what Nate and I are prioritizing this week for the editor.  I'll tag the two of you on the other tickets we're looking at this week as well.  If you see a reason for Nate not to work on one of these tickets, just post here.  Thanks!

**Comment by nslottow** [comment] 2016-11-02 22:22
I just implemented this the way I would expect it to work from the description and realized that it would change existing behavior.

Currently, when the timeline is open, the user is editing a subtitle, and then they press the 'enter' key, not only is the current subtitle deselected, but the next subtitle in the list is selected.

After using the 'enter' key to start editing the subtitle currently under the timeline cursor, I expect the 'enter' key to end the edit without selecting the next subtitle, so that I can use the enter key again to start editing the next subtitle under the timeline cursor after letting the video play for a bit.  This is a change from the current behavior.

Any thoughts about if this change will impact users negatively? Maybe it's a welcome change?

You can view and/or try out the change here: [gh-251](/pculture/unisubs/tree/gh-251)

**Comment by bendk** [comment] 2016-11-03 13:56
There's one use case where it's really nice to have enter go to the next subtitle: when you're translating subtitles from one language to another.  In that case you don't really care about the timeline, at least at first, you're just translating text.

I'm not sure how to make this work without hurting that use case, but I have a couple suggestions:
  - We select the next subtitle only if it has timings set.
  - We make alt-enter select the next subtitle.
  - We select the next subtitle if the video is not playing.

**Comment by PCF-Testing** [comment] 2016-11-04 11:22
So on the branch Enter key behaves in the editor in the following way:
- In Typing mode (whether transcribing adding new subtitle cells or translating in pre-created, timed cells) - pressing Enter moves the cursor into the next cell
- In Syncing mode - pressing Enter does nothing, editor responds only to TAB and Arrow Up/Down
- In Review mode:
* If the video is playing, Enter key pauses it and moves the cursor into the subtitle that is currently on screen
* If the user is editing the subtitle, Enter key finishes editing and moves the cursor out of the cell being edited. The video playback does not automatically resume - perhaps it should?

The described behaviour seems to make sense and be an improvement to the production version.

If we go ahead with merging this, we need to also update the help text in the editor:

- [ ] Help text in the bottom of the editing panel, with timeline ON only - remove "and move to next":
![subtitleeditor_pressentertosave](https://cloud.githubusercontent.com/assets/288455/20003857/c8f8ad8a-a299-11e6-8aba-a7fe19949f36.png)

- [ ] Update the text in the list of keyboard shortcuts - maybe change text to "Navigate to the next subtitle or edit the currently playing subtitle":
![subtitleeditor_keyboardshortcuts](https://cloud.githubusercontent.com/assets/288455/20003886/fef4149c-a299-11e6-81e9-4895c2b06108.png)

**Comment by kslottow** [comment] 2016-11-06 14:44
I learned from Dean this week that the Typing, Syncing, and Review modes are just guidelines for the captioners to know the steps they need to take; any changing behavior of keys is based on whether the timeline is open or closed - is this correct, @bendk ?

Current Enter behavior (on production):

- Timeline closed ( corresponds to Typing Mode), not currently editing a subtitle cell: adds new subtitle at end (appends subtitle).  
  - Looks like we are all agreed here - we don't need to change this because this scenario corresponds to transcribing or translating, in which you want to be able to keep moving from subtitle to subtitle easily; it's not the "reviewing and notice a typo" scenario.

- Timeline open (corresponds to Syncing and Review Mode), not currently editing a subtitle cell: does nothing.  
  - I think this should be as Maggie says it behaves in the branch: selects subtitle cell under the red timeline cursor, and pauses video if video is playing. The subtitle cell selection should happen whether or not the video is playing.

- Timeline open/closed, currently editing a subtitle cell: deselects current cell, **selects next subtitle cell**
  - I think we should revert to behavior on production here, and the video playback should not automatically resume.  If we changed either of these behaviors, it would interfere with the following use case, which I believe is fairly common*:
    - I am reviewing and press enter to select a subtitle so that I can split the subtitle into two (it's too long).  I copy the second line in the cell, then press enter.  I expect that the next subtitle will be selected, and the video will not resume playback.  I can then paste the copied line into the next subtitle cell, then press tab to begin video playback when I am ready.
  - I checked to see if, with the current behavior, "I can use the enter key again to start editing the next subtitle under the timeline cursor after letting the video play for a bit."  Actually, I can!  Steps for reproduction:

    -  finish editing a subtitle cell with the timeline open, press Enter.  The next subtitle cell will be selected for editing.
    - let the video play for a bit, then press Enter again.  The subtitle that is now under the timeline cursor will be selected for editing.

**Comment by PCF-Testing** [comment] 2016-11-07 11:12
Splitting lines is beyond the scope of this ticket and requires a separate shortcut. I think ENTER key should not have anything to do with it.

**Comment by kslottow** [comment] 2016-11-07 13:58
@PCF-Testing I agree!  I think I minced words in my last comment, so I deleted it and here is a more succinct version:

Ideal Enter behavior:
- **if currently editing a subtitle cell:** 
  - if video is playing: selects subtitle cell under red timeline cursor, video playback stops (new behavior)
  - if video is not playing: selects next subtitle cell, video playback not affected (original behavior)

- **if not currently editing a subtitle cell:**
  - Timeline closed: appends subtitle and selects appended subtitle for editing (original behavior)
  - Timeline open: 
    - selects subtitle cell under the red timeline cursor for editing (new behavior)
    - if video is playing, pause video (new behavior)

The note in the "Keyboard Controls" section of the GUI could be:

"Edit the currently playing subtitle, select the next subtitle, or insert one at the end"

This seems like a lot of behaviors for one key to have, but I can't justify removing the "select next subtitle" behavior because they are very useful when transcribing, translating, and splitting lines.

**Comment by PCF-Testing** [comment] 2016-11-08 16:50
>Timeline open:
>selects subtitle cell under the red timeline cursor for editing (new behavior)
>if video is playing, pause video (new behavior)

Bulk syncing untimed subtitles is a special sub-case of timeline open case - pausing the video and switching to editing a subtitle does not sound like perfect behaviour, at least for now, because bulk syncing does not handle interruptions well. If you pause a video during bulk syncing, the editor automatically ends subtitle where you pause the video and there is no good way to modify the end time until you make a second pass ("review") on subtitles. Perhaps until we can fix that, ENTER key better should not interrupt the syncing process.

**Comment by kslottow** [comment] 2016-11-15 15:12
@PCF-Testing good point.  I think there is already a good way to modify a subtitle endpoint after pausing during syncing, though:

- Pause a video during bulk syncing
- Play the video, and press the up arrow where you want the subtitle to end

**Comment by nslottow** [comment] 2016-11-30 22:07
I've updated the [gh-251](/pculture/unisubs/tree/gh-251) branch to reflect Maggie's requested help text changes.  

@bendk I didn't quite understand your concerns about this affecting translating.  When I add a new language to a video to translate from something that has existing subtitles, the timeline is defaulted to hidden, so as a translator I get the intended behavior of advancing to the next subtitle when I hit ENTER.  Are you talking about a slightly different use case?

As far as I can tell from the discussion, aside from addressing Ben's concerns, there isn't any functionality we'd like to add to this branch, so I'll move this into the testing pipeline.

**Comment by nslottow** [comment] 2016-11-30 22:16
@bendk I also spent some time trying to write a couple unit tests for this in [nslottow/gh-251-tests](/nslottow/unisubs/tree/gh-251-tests) but it didn't immediately seem worth the amount of time I was spending figuring out how to setup the state that the tests depend on, and mocking a keypress on the subtitles app itself.  I can put more time into this if you like, but seeing as there aren't unit tests for other hotkey actions, this didn't seem worth it.

**Comment by kslottow** [comment] 2016-12-01 19:31
>If you pause a video during bulk syncing, the editor automatically ends subtitle where you pause the video and there is no good way to modify the end time until you make a second pass ("review") on subtitles. Perhaps until we can fix that, ENTER key better should not interrupt the syncing process.

@PCF-Testing does the current behavior below seem like a good way to modify the end time in this scenario?  If so, we can use the fix Nate made and then make sure captioners are aware they can modify the end time in this way.

- Pause a video during bulk syncing
- Play the video from where it was paused. 
- Press the up arrow to reset the subtitle endpoint.

**Comment by PCF-Testing** [comment] 2016-12-02 11:11
This scenario is not perfect because after resuming playback and pressing Arrow Up the next subtitle will not start automatically and the normal bulk sync flow will be interrupted.

I think we should now release the changes already made on gh-251 and return to this issue once a permanent fix for the problem with pausing in the middle of bulk syncing (is it https://github.com/pculture/unisubs/issues/2648?) is ready.

I am about to make a pull request for gh-251 unless anyone vehemently disagrees.

**Comment by kslottow** [comment] 2016-12-02 22:08
@PCF-Testing Sounds good to me.  The change seemed so simple at first, but it's awkward enough given current workflows in the editor that we should not try to force it.

**Comment by PCF-Testing** [comment] 2016-12-03 00:20
Made a pull request.

**Comment by PCF-Testing** [comment] 2016-12-22 04:01
Deployed.

**Closed by PCF-Testing** 2016-12-22 04:01 UTC
Labels: new editor, type: feature
