### ISSUE TITLE
Embed Code dispenser broken! No data-url is empty!

### ISSUE THREAD

**Issue by jeremyclarke** [pculture/unisubs#2103] opened 2015-03-09 15:58 UTC
Hi guys, hopefully it hasn't been this way for too long, but right now (15:53 GMT Mar 9 2015) the "Get Embed Code" button seems to be completely broken. 

Here's a video:

http://www.amara.org/en/videos/SvoJipcJJH1x/info/panorama-iedereen-een-basisinkomen/

Here's the code it gives me:

<div class="amara-embed" data-height="px" data-width="px" data-url="">
</div>

This is totally confusing since there's no data-url and thus nothing will happen with this code. Users will definitely be expecting that the "Get embed code" button will give you the specific embed code for the video they are looking at, so getting that URL in there is mandatory. 

Additionally there must be a lot of people who don't understand that the data-height and data-width values are intentionally broken by default. Many users have no ability to read HTML attributes and understand the key->value relationship, so if you expect people to edit this code manually you need to be very specific with them. I'd suggest adding sensible default values rather than leaving it empty, so that they at least get a working player after pasting, and can see the numbers next to width/height which would help them understand what to edit. (On a related note, the width/height values should be empty by default which should result in a responsive embed without absolute size. That upgrade would make this whole issue mostly moot).

**Comment by jdragojevic** [comment] 2015-03-09 16:01
This is a duplicate of #1968 which was merged today and will go out with our next deploy.

related issue about responsiveness I see you covered in #2102.

**Closed by jdragojevic** 2015-03-09 16:01 UTC

**Comment by jeremyclarke** [comment] 2015-03-09 16:05
Thanks and sorry for adding noise :)
