### ISSUE TITLE
API caps video URLs at 255 characters

### ISSUE THREAD

**Issue by nateabele** [pculture/unisubs#2248] opened 2015-06-11 01:10 UTC
We have a commercial media system in which we use CloudFront signed URLs, hence, the URLs regularly exceed 255 characters. However, attempting to submit these to the API returns a 500 based on an underlying database constraint. My colleague recorded a video demo trying to work through it:

https://www.dropbox.com/s/etfqwdt4vrzv8zr/amara-bug.mp4

Thanks for your time. /cc @warrenseymour

**Comment by syl22-00** [comment] 2015-06-11 10:25
So my understanding of what happens and how this could be fixed is:
Since collation is utf8, if a `varchar` has a `max_length` of 255, it considers that the key is 255*3 (max bytes per character in utf8) = 765. So if we increase to just 256, then we get over the limit of (foreign) keys (767).

The thing is that URLs are supposedly ASCII, so 1 byte per character (at least internally as characters outside ASCII are encoded by the browser). So we should be able to use URLs up to 767 character-long, but that assumes we adjust the collation.

I tried to change the collation of the table:
```
alter table videos_videourl character set ascii collate ascii_general_ci;
```
After that, the migration runs fine (I mean the migration you first tried to run in your example video after changing from 255 to 512: `url = models.URLField(max_length=512)`). It does not work to change the collation of only the url column.

@bendk do you think that's something we should do?

**Comment by bendk** [comment] 2015-06-11 13:06
Changing the collation makes sense to me.

What's a good max length 1024?  2048?  I believe that at some point we run into the maximum mysql row length, in which case we should switch to a text column.  But I think a large varchar should work.

**Comment by syl22-00** [comment] 2015-06-11 13:24
I think we are limited to 767 characters because it is a foreign key. If we try to change the current max_length to a greater value without changing the collation, running the migration would give the following error:
```
django.db.utils.DatabaseError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

**Comment by syl22-00** [comment] 2015-06-11 15:43
OK, so as we discussed, this should be fixed in branch gh-2248 with:
. one migration to change collation of the videos_videourl table
. one model change and associated migration to change the max length of urls to 512

**Comment by jdragojevic** [comment] 2015-06-16 18:40
@syl22-00 When I run dev dbreset, I get this error in the log:

```
Creating table videos_videourl
Traceback (most recent call last):
  File "manage.py", line 42, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 90, in handle_noargs
    syncdb.Command().execute(**options)
  File "/usr/local/lib/python2.7/dist-packages/raven/contrib/django/management/__init__.py", line 37, in new_execute
    return original_func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 102, in handle_noargs
    cursor.execute(statement)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.DatabaseError: (1071, 'Specified key was too long; max key length is 767 bytes')
Removing unisubs_app_run_1...

```

Also previously when I had run the migration on my existing database and tried to then add a long url, I got this error: 

```
Exception Type: Warning at /videos/create/
Exception Value: Data truncated for column 'url' at row 1
```

**Comment by warrenseymour** [comment] 2015-06-18 13:15
@syl22-00 @jdragojevic I can confirm that I get the same error ('Specified key was too long; max key length is 767 bytes') when I attempt to perform a dbreset on this branch

**Comment by syl22-00** [comment] 2015-06-19 17:19
Sorry for not having gone back to this earlier. What I think is happening is that with dbreset, we actually just create the tables without going through migrations (they are faked), as they should not be necessary as the content is initially empty.

The problem is that we do the collation change introduced in that ticket in a migration, so it is not applied, and we get the key length issue when creating the tables.

Supposedly, we could make it work with first calling syncdb (without `--all`, to create the tables that do not have migrations), then `migrate` (without `--fake`).

However syncdb does not work without, and complains with:
```
django.db.utils.DatabaseError: (1146, "Table 'amara.auth_permission' doesn't exist")
```
So I am still searching the right way to make that work.

**Comment by bendk** [comment] 2015-06-19 17:29
I think you might be able to do it with init_command (search for it here https://docs.djangoproject.com/en/1.4/ref/databases/)

If you set the default colation with init_command, then maybe things would work.

**Comment by syl22-00** [comment] 2015-06-19 17:54
Thanks @bendk, the thing is that it sets the collation to the whole database, and our migration was changing it only for one table (the video URL).

**Comment by syl22-00** [comment] 2015-06-22 14:52
So another attempt to resolve this is in branch gh-2248-alt. Since the issue came from a `unique_together` meta parameter, I replaced it by an overloaded `validate_unique` function in the model. `unique_together` was making an index of the two fields, hence introducing the index length constraint. The overloaded `validate_unique` just makes a database query to see if there is already an existing record with the same `(url, type)`.

* `init_command` suggested earlier did not work as it happens before the table is created.
* Another possible resolution came from a [stackoverflow answer to me asking for help](http://stackoverflow.com/questions/30969101/key-longer-than-255-chars-in-a-utf8-mysql-database). My question was not very correct (I forgot to mention the issue came from `unique_together`), so the answer to put the fields to be unique into another  table is probably an overkill for us as we already has a lot of date that would need to be migrated.

**Comment by jdragojevic** [comment] 2015-06-22 16:44
Here is a [test url that has 403 characters](https://s3-us-west-2.amazonaws.com/dragojevic-test/thisisareallylongnameforafoldersothatIcantesthowobnoxiouslylongurlsicanmakethatamaracanhandleandstilladd/thisisareallylongnameforafoldersothatIcantesthowobnoxiouslylongurlsicanmakethatamaracanhandleandstilladd/thisisareallylongnameforafoldersothatIcantesthowobnoxiouslylongurlsicanmakethatamaracanhandleandstilladd/translating_subtitles_with_amara.mp3) that I can import into amara using the gh-2248-alt branch.

**Comment by syl22-00** [comment] 2015-06-26 13:19
So after discussing it with @bendk that solution was not convincing as-is because the index on URLs was actually very useful. So, in branch gh-2248-indexes, we have:

* A unique constraint in the database on `(url(255), type)`, meaning that we have an index on a prefix of the url. This constraint is set on the database through a raw SQL command, in a migration, but also in a management command so that it can be run even when bootstrapping the database, when migration are not run.
. Removed the over-ridden `validate_unique`, which is not useful anymore.
. The `dbreset` command to bootstrap the database also runs the new manage command that adds the indexes (needed otherwise index would never be added if the migration was not run).

**Comment by nateabele** [comment] 2015-06-27 22:50
> [...] we have an index on a prefix of the url

Meaning, on the URL without querystring?

**Comment by syl22-00** [comment] 2015-06-28 20:45
@nateabele not exactly, meaning the first n characters of the field (in our case 255).

**Comment by nateabele** [comment] 2015-06-29 03:13
Can you explain the purpose of the unique constraint? As I mentioned above, we use CloudFront signed URLs, which means the URL is unique per video per 24-hour period. I'm concerned this is going to break some other part of the system.

**Comment by bendk** [comment] 2015-06-29 13:16
Basically, we use the unique constraint to not create 2 videos objects in Amara for the same URL.  So if one person submits the URL, creates subtitles, then a second person submits the same URL, they will see the first person's subtitles.  (Actually, it's a constraint on URL + video type but the difference isn't very significant)

The only thing that could see as as issue with your system is that you are creating a new URL for the same video.  If you want to keep the subtitles for the old URL, then you'll need to make sure you:
 * associate the new URL with the exsting video
 * make the new URL the primary URL
 * optionally delete the old URL.

**Comment by bendk** [comment] 2015-10-23 15:51
Is this fixed?  If not what else do we need to do?

**Comment by syl22-00** [comment] 2015-10-23 16:00
This was fixed and merged:
https://github.com/pculture/unisubs/pull/2269

**Closed** 2015-10-23 16:04 UTC
