### ISSUE TITLE
IntegrityError: (1062, "Duplicate entry '0-1160699-43' for key 'teams_application_status_40ba08049a788bad_uniq'")

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3042] opened 2017-12-04 14:23 UTC
https://sentry.io/pculture/unisubs/issues/413032217/

```
IntegrityError: (1062, "Duplicate entry '0-1160699-43' for key 'teams_application_status_40ba08049a788bad_uniq'")
(12 additional frame(s) were not displayed)
...
  File "teams/new_views.py", line 130, in wrapper
    return view_func(request, team, *args, **kwargs)
  File "teams/new_views.py", line 574, in join
    return application_form(request, team)
  File "teams/new_views.py", line 594, in application_form
    form.save()
  File "teams/forms.py", line 1677, in save
    self.application.save()
  File "teams/models.py", line 1852, in save
    super(Application, self).save(*args, **kwargs)

IntegrityError: (1062, "Duplicate entry '0-1160699-43' for key 'teams_application_status_40ba08049a788bad_uniq'")
```

**Comment by bendk** [comment] 2017-12-04 14:23
@asabine can you take a look at this one since you've been working with applications lately?  Maybe it's caused by a user signing up twice using the application page.

**Comment by asabine** [comment] 2017-12-04 14:27
that seems like it would be the issue; i can take a look later this sprint if i have time

**Comment by asabine** [comment] 2018-01-05 19:30
it should catch the IntegrityError now and return an error message in the event this happens again; it shouldn't, since the view checks for existing applications before the form is ever rendered, but there may be instances where a request goes through twice by accident when submitting

**Comment by PCF-Testing** [comment] 2018-01-08 12:34
@asabine: do you know what scenario would lead to this error?

**Comment by asabine** [comment] 2018-01-08 14:03
@PCF-Testing when a user submits an application form twice before the first request is fully processed

**Comment by PCF-Testing** [comment] 2018-01-09 09:21
Could not reproduce the original issue because the system would not allow submitting an application to the same team twice, but the application process functions on the branch and all the unit tests pass, so marking as Needs PR.

**Comment by PCF-Testing** [comment] 2018-01-19 02:33
Deployed.

**Closed by PCF-Testing** 2018-01-19 02:33 UTC
