### ISSUE TITLE
Consider making video search insensitive to accents

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2366] opened 2015-09-30 12:37 UTC
This is a feature suggestion we received regarding finding videos with the search feature on the TED team page.

```
There was a change in the TEDx-video naming rules a while ago, where TED
allowed organizers to use accented letters in the name of their event.
For this reason, I would suggest that implementing such character substitution
would be a good idea, since right now, people won't be able to find all the
talks from an event if they just use either the accented version or the one
without accents.

Examples:

Video search:
TEDxKrakow (65 videos)
http://amara.org/en/teams/ted/videos/?page=1&lang=any&project=any&lang-mode=%2B&sort=-time&q=TEDxKrakow

TEDxKraków (72 videos)
http://amara.org/en/teams/ted/videos/?page=1&sort=-time&q=TEDxKrak%C3%B3w&lang=any&lang-mode=%2B&project=any

Video search: Rafał Styczeń (1 result)
http://www.amara.org/en/teams/ted/videos/?project=any&lang-mode=%2B&q=Rafa%C5%82+Stycze%C5%84
Video search: Rafal Styczen (not found)
http://www.amara.org/en/teams/ted/videos/?project=any&lang-mode=%2B&q=Rafal+Styczen

Member search: Matti Jääaro (1 result)
http://www.amara.org/en/teams/ted/members/?assignee=&project=&lang=&q=Matti+J%C3%A4%C3%A4aro
Member search: Matti Jaaaro (not found)
http://www.amara.org/en/teams/ted/members/?assignee=&project=&lang=&q=Matti+Jaaaro
```

Some thoughts:
- It may improve search experience overall, even if it causes some false positives. 
- For some languages like Polish it's not uncommon to fill forms with ASCII characters only.
- It may make sense to enable it selectively. Searches with multiple accents may have to look up a lot of combinations and end being slow.

**Comment by bendk** [comment] 2015-11-18 20:00
This seems to have gotten fixed as a sideeffect of the changes in the gh-838 branch.

**Comment by PCF-Testing** [comment] 2015-11-21 13:50
Seems to be fixed to me, too.

**Comment by PCF-Testing** [comment] 2015-12-24 13:04
Still an issue on production after deployment of #838.

**Comment by bendk** [comment] 2015-12-28 16:33
#838 isn't fully deployed yet, I expect this will be fixed once it is.

**Comment by kslottow** [comment] 2016-12-07 18:46
@PCF-Testing is this issue resolved?

**Comment by PCF-Testing** [comment] 2016-12-08 03:00
@kslottow: no

**Comment by kslottow** [comment] 2016-12-08 16:04
thanks @PCF-Testing - just doing some housekeeping here to see what's done and not.

**Comment by bendk** [comment] 2016-12-08 16:09
@PCF-Testing what isn't working?  I just tried that video search at the top of the list and the results seemed the same for TEDxKrakow and TEDxKraków.

I'm guessing the member search is still sensitive to the accents, but that seems like a different issue to me.

**Comment by PCF-Testing** [comment] 2016-12-09 01:18
@bendk: the other two searches from Fran's list, including search by speaker's name

**Comment by bendk** [comment] 2016-12-20 21:04
Ahh yeah, so that makes sense to me.  We fixed this for video search, but non user search.  I just made a separate ticket for the user search issue (#2708).

**Comment by PCF-Testing** [comment] 2016-12-21 02:12
@bendk: How about searching in videos by speaker's name? There is no other ticket for this.

**Comment by bendk** [comment] 2016-12-21 15:26
I was thinking the other ticket covered it, since the code-wise it's pretty much automatic once you implement the changes for user search.  I'll add a note to the ticket to make sure we remember that.

**Comment by bendk** [comment] 2016-12-21 15:31
Ignore my last comment.  I think speaker name should actually be covered by the current code.  Maybe it's the particular accented charactor?  Can you test this out more?  What if the speaker name is "TEDxKraków"?  What if the title is "Rafał Styczeń"

**Comment by PCF-Testing** [comment] 2016-12-22 11:06
@bendk: Checked this a bit more and found you were right - the problem was indeed in particular characters, rather than in title vs. speaker name. In particular, with "Rafał Styczeń" appearing in title or speaker name, "Styczen" successfully finds both entries, while "Rafał" returns none. So the cause is that "l" is not treated as an equivalent of "ł"; not sure if this is fixable or is actually worth the effort fixing...

**Comment by bendk** [comment] 2016-12-22 14:43
Yeah, I just tested the way I would do it and it doesn't fold "ł" either.  I'm not sure it's even correct to try folding that one.  I'm going to close this one again then.

**Closed by bendk** 2016-12-22 14:43 UTC
Labels: type: feature
