### ISSUE TITLE
Transcriber / translator cannot assign their subtitles for review, regardless of permissions

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1932] opened 2014-12-30 05:54 UTC
Steps to reproduce:
1. As a TED manager or admin, complete and submit a transcription or translation task.
2. Attempt to assign the resulting Review task to a particular user. "Assign" link will not be available.

Reported in: http://ted-support.amara.org/helpdesk/tickets/77111

**Comment by PCF-Testing** [comment] 2015-01-08 11:38
The problem only exists for THEIR OWN subtitles, i.e. if a language coordinator (aka manager) has created and submitted a translation, she cannot assign it to a particular reviewer.

I have been able to reproduce this issue with the use of this scenario.

**Comment by jdragojevic** [comment] 2015-01-08 15:24
If the user is a team manager or admin - if they have performed the transcription task, then they don't have the permission to perform the review task, nor assign it.

Instead they see this:

![image](https://cloud.githubusercontent.com/assets/299270/5664674/6df6f562-9752-11e4-8a79-bf9c59c84e59.png)

Seems like only an owner has the ability to review or assign work for review tasks where they have performed the transcription task.

**Comment by bendk** [comment] 2015-01-08 16:33
Ok, so I can reproduce this one now.  By the way, the admin may or may not see the link depending on a fairly obscure rule.

I can change it, but I'm a bit hesitant to make any changes to the tasks system because it's hard to know what the fallout will be.  For example, we don't allow managers to review their own work, but after the change I believe they could get around that rule by assigning it to themselves, then performing the task.

On a related note, should managers be allowed to review their own work?  If we changed that rule, then the assignment issue would be fixed automatically.

**Comment by PCF-Testing** [comment] 2015-01-09 07:36
No, nobody should be able to review their own work - this is essentially what the idea of review is about, having another pair of eyes go over the subtitles.

However, we made a sole exception for team owners, to make sure that subtitles do not get stuck at review stage if there is nobody else except the owner at some time in a team. Others should not be able to review, but team managers and admin need to be able to appoint reviewers at will to speed up the review process.

I am pretty sure that if managers/admins get access to Assign link on review tasks for their own subtitles, they won't be able to select themselves in the member pick tool - there should be some protection in the code for that.

**Comment by bendk** [comment] 2015-01-16 20:26
Okay, this is implemented in the #1932 branch.  You are right that a user can't assign tasks to themselves.  I think this one should be all set, but any time we change the tasks code I think we should run the full selenium suite.

**Comment by jdragojevic** [comment] 2015-01-22 17:46
@bendk - fallout from this appears to be in the rollback tests where the transcriber completes the task, and still has the rollback button available.

**Comment by jdragojevic** [comment] 2015-01-22 17:56
I'll have to look into this further.  It appear correct on the preview build, 1932.amara.org.

**Comment by jdragojevic** [comment] 2015-01-22 21:09
@bendk - so whether or not the user has permission to perform the rollback, seems to be tied to whether or not they have permissions to assign tasks in the workflow settings.  

It's a pretty bizarre linking but I don't think it will have any side-effects on any of our existing  teams.

**Comment by bendk** [comment] 2015-01-22 21:57
So is this good to go?  If not, what changes do I need to make?

**Comment by PCF-Testing** [comment] 2015-01-23 02:41
Rollback tied to permission to assign tasks does not make much sense, IMO. Should be governed by the permission to edit, since it is basically equivalent to editing subtitles (creating a new version).

Should I make a new ticket for this?

**Comment by jdragojevic** [comment] 2015-01-23 08:47
I agree that it doesn't make sense, but I also don't want to get bogged down in the weird details of the tasks system, when we are trying to move away from it.  Since every change always has crazy side effect, I'm OK with keeping this as-is for now, since it isn't going to have an effect on the current setup of task teams.

**Comment by jdragojevic** [comment] 2015-02-17 09:15
this was fixed and deployed.

**Closed by jdragojevic** 2015-02-17 09:15 UTC
Labels: req: partner, status 2:  fixed
