### ISSUE TITLE
As a subtitler, the help tray should always be visible.

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2637] opened 2016-09-27 18:11 UTC
When your subtitles reach the bottom of the screen, the “help tray/gutter” is no longer completely visible.  You can manually scroll down to see it, but this is highly impractical if you are typing quickly to keep up with the speaker.  Ideally, you should not have to use the mouse pad at all in the Typing stage.

![automated scroll down](https://cloud.githubusercontent.com/assets/22455700/18885942/655cde1c-84b3-11e6-8a9c-4acd39089e4a.png)

live demo: https://drive.google.com/file/d/0B9QDmkwjoAewYUNic19XRkFSTUU/view?usp=sharing

**Comment by kslottow** [comment] 2016-10-05 22:09
@bendk this is one of the editor features that Nate and I thought seemed pretty straightforward and would have an immediate benefit.  Just making sure this doesn't overlap/interfere with anything that's currently being worked on?

**Comment by kslottow** [comment] 2016-10-06 19:31
Two options/fixes:
-make bottom of help tray align to bottom of window when subtitles have scrolled down that far
-automatically scroll subtitle editor and keep help tray aligned with subtitle editor (active subtitle always in middle of screen)

**Comment by nslottow** [comment] 2016-10-09 20:13
I noticed that the "Press ENTER to save subtitle and move to next" line also gets cut off every other time I press enter when editing a subtitle at the bottom of the screen.  Is that the intended behavior? It seems like it could be related to this bug, but it could also just turn out to a separate issue.  It also gets cut off when I select a subtitle with > 3 lines while the editor window is full of subtitles, and the height of the subtitle expands to show all the lines.

**Comment by nslottow** [comment] 2016-10-09 20:33
The fix for this issues seems to be a matter of getting `positionInfoTray()` in module `amara.SubtitleEditor.subtitles.directives` called at all the proper times .  Simply calling it after each text edit keystroke doesn't seem to be good enough, since some parts of the info tray get updated after processing the root scope 'text-edit-keystroke' event.  I'll continue to look into finding the proper hook, ideally after the info-tray view is completely done updating as the result of a text edit.

**Comment by kslottow** [comment] 2016-10-10 00:46
@nslottow just checked out the "press ENTER to save subtitle and move to next" thing.  Pretty positive that's not the intended behavior.  If it is related to this bug, it would be great to fix both.  I don't think we need to worry about the other scenario (>3 lines) because all subtitling guidelines specify 2-3 lines only.

Sounds good, let's continue working on this next weekend.  Can you reset your estimates for this and the autopause implementation to reflect actual hours spent?  That way we can start building some historical data for accurately setting up sprints.  Thanks!

@bendk just wanted to make you aware that we're working on this issue, in case you have any insights or comments.  Thanks!

**Comment by nslottow** [comment] 2016-10-10 02:20
@kenzie I'm not quite ready to reset the estimates for this and the auto-pause implementation/I don't think I have enough data to make any meaningful changes.  To me they are both still 1's, perhaps the auto-pause tests got close to a 2 but that doesn't mean much to me without more completed tasks to compare to.

**Comment by nslottow** [comment] 2016-10-20 16:16
@PCF-Testing I've pushed branch gh-2637 to be tested as we discussed in #2669. Thanks!

**Comment by PCF-Testing** [comment] 2016-10-21 13:26
@nslottow: could you please merge in the latest changes from staging? gh-2637 is behind

**Comment by nslottow** [comment] 2016-10-23 07:59
Sure thing, just pushed the changes to [pculture/unisubs branch gh-2637](/pculture/unisubs/tree/gh-2637)

**Comment by PCF-Testing** [comment] 2016-10-25 09:25
Looks fine, making a PR for the branch.

**Comment by PCF-Testing** [comment] 2016-10-25 14:26
I'll close this one when it goes live and the release notes get posted.

**Comment by PCF-Testing** [comment] 2016-10-31 09:48
Deployed.

**Closed by PCF-Testing** 2016-10-31 09:48 UTC
Labels: new editor, type: feature
