### ISSUE TITLE
Javascript errors opening the editor

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1637] opened 2014-08-07 15:39 UTC
Several users have reported issues opening the editor.  Here's a screenshot of the console when this happens:

![image](https://cloud.githubusercontent.com/assets/1012809/3844424/06b429f6-1e49-11e4-9660-92c05223f73d.png)

**Comment by PCF-Testing** [comment] 2015-01-21 07:07
Got a tip from users that this issue consistently appears on Windows 8.1.

Could reproduce with my own instance of Windows 8.1 as follows: 
- The editor fails to load across all the browsers
- The editor only fails to load if a video already has some subtitles. If a video has none, and the first language is about to be added, the editor loads nicely as usual
- The computer / system is brand new and free of suspicious software (plug-ins, malware, firewalls) 
- JavaScript console displays a number of errors, as shown on the screenshot below:

![loadingeditorscreenshot](https://cloud.githubusercontent.com/assets/288455/5832350/c11a699a-a0f8-11e4-93f0-c809db81277f.png)

Ticket: http://ted-support.amara.org/helpdesk/tickets/77585

Setting status to critical, since it affects a major operating system and the majority of use cases for subtitle editing.

**Comment by jdragojevic** [comment] 2015-01-21 08:21
I'm going to drop this from critical and mark it as important.  If google can be believed, < 1% of the visitors to the editing pages are using windows 8.1.

**Comment by jdragojevic** [comment] 2015-01-21 08:37
@PCF-Testing I ran a test of this via sauce-labs, https://saucelabs.com/tests/ad4a5d3d855b4d43a38f71243f7ec2c7 and could not reproduce. 

Could you try to do the same?  I sent you an account invite in case you don't have one already.

**Comment by PCF-Testing** [comment] 2015-01-21 09:22
Looks OK for me on sauce-labs, but with a real OEM installation of Win8.1 on a brand new Lenovo laptop failing to work with the subtitle editor, it seems that the emulation might be missing something important.

Lack of Windows 8.1 users could be caused exactly by the fact that Amara editor is incompatible with this OS, except for viewing subtitles created by others.

The problem is quite widespread; there are a few currently open tickets on this issue.

**Comment by syl22-00** [comment] 2015-01-21 11:09
It also works fine for me on Chrome on Windows 8.1 pro. 

@PCF-Testing would you mind trying launching chrome with extensions disabled? (using `--disable-extensions`). Also could check if launching with disabled extensions removes the sf_main.jsp error on other pages.

**Comment by jdragojevic** [comment] 2015-02-05 08:15
I think we are back to this being an issue with specific plugins. Closing.  We should make a new ticket for any new issues that come up.

**Closed by jdragojevic** 2015-02-05 08:15 UTC
Labels: pri:  important, status 1: in-progress

**Comment by franontanaya** [comment] 2015-02-07 14:42
For reference, I've got an identical report and screenshot from an user running Chromium on Ubuntu, so I don't think this was OS specific.
