### ISSUE TITLE
Allow removing time for a video

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2869] opened 2017-07-03 20:34 UTC
Suppose a user has a video with subtitles, but they decide to remove a part of it.  For example, removing a 30 second intro, or 10 seconds in the middle.

We should have a way for users to delete the time in the video.  This means:
  - The user has a way to open the "Remove time" form
  - User selects a start time and an amount of seconds to remove
     - Maybe the start time defaults to the current position in the video
  - User clicks "Delete time" button
  - We delete any subtitles inside that time frame.
    - If a subtitle is partly inside timeframe, then we should clip it so that only the time outside remains
  - Any subtitles after the time frame are moved backward in time by the amount of time selected

**Comment by kslottow** [comment] 2017-07-03 20:59
@kslottow note to self - check Premier, Final Cut, Ableton versions of how to do this, and confirm that this solution covers the use case for clients

**Comment by kslottow** [comment] 2017-11-10 16:08
duplicate of #1610

**Closed by kslottow** 2017-11-10 16:08 UTC
