### ISSUE TITLE
NotImplementedError: subclasses of ListFilter must provide a queryset() method

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3409] opened 2018-09-14 14:04 UTC
https://sentry.io/pculture/unisubs-staging/issues/686379515/

```
NotImplementedError: subclasses of ListFilter must provide a queryset() method
(7 additional frame(s) were not displayed)
...
  File "django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "django/contrib/admin/options.py", line 1485, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "django/contrib/admin/views/main.py", line 109, in __init__
    self.queryset = self.get_queryset(request)
  File "django/contrib/admin/views/main.py", line 364, in get_queryset
    new_qs = filter_spec.queryset(request, qs)
  File "django/contrib/admin/filters.py", line 49, in queryset
    raise NotImplementedError('subclasses of ListFilter must provide a queryset() method')

NotImplementedError: subclasses of ListFilter must provide a queryset() method
```

**Comment by PCF-Testing** [comment] 2018-09-15 10:59
The page works now.

**Comment by PCF-Testing** [comment] 2018-09-18 00:42
Marking as closed because this is a regression issue.

**Closed by PCF-Testing** 2018-09-18 00:42 UTC
