### ISSUE TITLE
Glitch in dragging subtitle in/out times

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#1592] opened 2014-07-10 21:26 UTC
In the timeline, there is are spaces around the edge of the subtitle where if you click and drag, it moves the timeline and not the subtitle. This has been experienced on Firefox and Chrome in Mac osx.

The most painful part of this glitch is when it happens near an in/out point of a subtitle, and happens when a user is attempting to modify the in/out point, but instead moves the timeline.

Steps to reproduce:
1) Open editor and open timeline
2) On a subtitle in the timeline click and drag just a touch to the inside of an in/out point

Here's a screenshot of the places where click and dragging affects the timeline and not the subtitle:

![click and dragging](https://cloud.githubusercontent.com/assets/5092242/3545434/a082adde-0876-11e4-805a-3fa8ca16c04b.png)

**Comment by kslottow** [comment] 2016-10-20 15:07
#2638

**Comment by kslottow** [comment] 2016-10-20 15:20
@darren-bridenbeck In the referenced issue #2638 we'll address the left and right rectangles above.  

@nslottow I followed Darren's steps to reproduce and it is still an issue.  It appears that the subtitle is only selected if you hover directly over the text, but we should include the top and bottom of the subtitle in the "move whole subtitle" dragging area (distinct from endpoint dragging areas).

**Comment by nslottow** [comment] 2016-10-20 21:16
Closing this as a duplicate of #2638.  There's more context there.

**Closed by nslottow** 2016-10-20 21:16 UTC
Labels: new editor
