### ISSUE TITLE
Install redis and use it to track team stats

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3247] opened 2018-06-06 14:20 UTC
We want to add a stats page to collab teams, although we're not sure exactly how it should work.  In the meantime we should start tracking stats.  I think we should use something like this:
 - Add redis as a dependency
 - Add some generic code to store counters for things.  Something like this: https://redislabs.com/ebook/part-2-core-concepts/chapter-5-using-redis-for-application-support/5-2-counters-and-statistics/5-2-1-storing-counters-in-redis/
 - Add counters for various team stats:
   - Videos added
   - Members added
   - Subtitles completed
     - Segment by language

**Comment by bendk** [comment] 2018-08-01 17:04
This one is implemented in the tasktiger branch, since I want to do it together with #3304.

To test:
 - Run `dev build` .  You might also need `docker-compose stop`.
 - Add some team members, videos to a team and also publish some subtitles
 - There's no real UI around this yet, but you can see the raw stats by going to `/teams/[slug]/debug-stats/`.  There's a link to there when you control-click the team header.
 - Stats are cached per-day, since we typically will only use them to get counts for yesterday, last week, and last month.  So run `dev manage clear_cache` before checking that page.

**Comment by bendk** [comment] 2018-08-08 13:51
I'm actually going to call this branch `redis` instead of `tasktiger`, since we're going to be using rq instead of tasktiger.   I'm going to move this out of testing though, since I'm still working on it.

**Comment by PCF-Testing** [comment] 2018-08-10 10:31
redis branch fails to build for me, in contrast with other branches. The error is as follows:

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxcursor/libxcursor1_1.1.14-1ubuntu0.14.04.1_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 158 MB in 57s (2757 kB/s)
The command '/bin/sh -c apt-get -y --force-yes install wget python-dev python-setuptools make gcc libmysqlclient-dev supervisor libxml2-dev libxslt-dev zlib1g-dev swig libffi-dev libssl-dev libyaml-dev git-core python-m2crypto subversion openjdk-6-jre libjpeg-dev libfreetype6-dev gettext build-essential gcc dialog mysql-client node-uglify ruby-sass libav-tools libz-dev pkg-config lua5.2 liblua5.2-dev lua-cjson' returned a non-zero code: 100
Traceback (most recent call last):
  File "/home/maggie_s/unisubs/bin/build.py", line 38, in <module>
    main(sys.argv)
  File "/home/maggie_s/unisubs/bin/build.py", line 35, in main
    run_docker_build(args.image_name, args.no_cache)
  File "/home/maggie_s/unisubs/bin/build.py", line 23, in run_docker_build
    subprocess.check_call(cmdline)
  File "/usr/local/lib/python2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '-t', 'amara-app', '/home/maggie_s/unisubs']' returned non-zero exit status 100

**Comment by PCF-Testing** [comment] 2018-08-13 10:39
This branch behaves weirdly.

I have been able to see the numbers of team members  and videos added to the team, but not the numbers of approved and published collabs. Then I left the app idle for a day or so, and now it keeps displaying the following error:

OperationalError at /teams/collab-test/debug-stats/
(1040, 'Too many connections')
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/teams/collab-test/debug-stats/
Django Version:	1.7.11
Exception Type:	OperationalError
Exception Value:	
(1040, 'Too many connections')
Exception Location:	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in __init__, line 193
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  204.                 response = middleware_method(request, response)
File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/middleware.py" in process_response
  129.                 panel.generate_stats(request, response)
File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/request.py" in generate_stats
  55.                             for k in sorted(request.session.keys(), key=force_text)]
File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py" in keys
  120.         return self._session.keys()
File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py" in _get_session
  182.                 self._session_cache = self.load()
File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/cached_db.py" in load
  44.                     expire_date__gt=timezone.now()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in manager_method
  92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in get
  351.         num = len(clone)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in __len__
  122.         self._fetch_all()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in _fetch_all
  966.             self._result_cache = list(self.iterator())
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
  265.         for row in compiler.results_iter():
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in results_iter
  701.         for rows in self.execute_sql(MULTI):
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  785.         cursor = self.connection.cursor()
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py" in cursor
  165.             cursor = self.make_debug_cursor(self._cursor())
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py" in _cursor
  138.         self.ensure_connection()
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py" in ensure_connection
  133.                 self.connect()
File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py" in __exit__
  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py" in ensure_connection
  133.                 self.connect()
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py" in connect
  122.         self.connection = self.get_new_connection(conn_params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py" in get_new_connection
  472.         conn = Database.connect(**conn_params)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py" in Connect
  81.     return Connection(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py" in __init__
  193.         super(Connection, self).__init__(*args, **kwargs2)

Exception Type: OperationalError at /teams/collab-test/debug-stats/
Exception Value: (1040, 'Too many connections')

Running bin/dev manage clear_cache did not help.

**Comment by bendk** [comment] 2018-08-13 13:33
That looks like a mysql error.  I'm pretty sure I didn't change anything there, so if that's the only issue you're seeing I think we can merge to dev and test it on a real instance.

**Comment by PCF-Testing** [comment] 2018-08-14 09:04
After restarting and experimenting a bit more, I think I have figured out what the problem is.

/debug-stats/ page only gets generated once for the actions that had been committed before opening that page. Once you have loaded /debug-stats/ and reviewed the statistics, any subsequent actions won't get added to the stats.

Example: you run bin/dev up, then add several users to a team and approve a subtitle request. Next, you open /debug-stats/ and find those actions on the page. Next, you add some videos to the team and refresh /debug-stats/, but the added videos won't get added to the statistics. This feels like a bug to me.

Also, I am not sure I understand how "Last week" and "Last month" are defined. Suppose today is Tuesday. Actions committed today appear only in "Today" column, "Last week" and "Last month" all display 0s. But if the same actions were performed yesterday (i.e. on Monday), they get added to "Yesterday", "Last week" and "Last month". Is this as expected? Feels a bit weird. I'd probably expect "Last week" to show stats for the last 7 days, including today, and "Last Month" for the last 30 days, including today.

Finally, endorsing subtitles through the subtitle editor raised the following exceptions:
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/opt/apps/amara/apps/videos/views.py", line 652, in subtitles
app_1            |     return render(request, 'future/videos/subtitles.html', context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 50, in render
app_1            |     return HttpResponse(loader.render_to_string(*args, **kwargs),
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 178, in render_to_string
app_1            |     return t.render(context_instance)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
app_1            |     return self._render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 88, in instrumented_test_render
app_1            |     return self.nodelist.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
app_1            |     bit = self.render_node(node, context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
app_1            |     return node.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 126, in render
app_1            |     return compiled_parent._render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 88, in instrumented_test_render
app_1            |     return self.nodelist.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
app_1            |     bit = self.render_node(node, context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
app_1            |     return node.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
app_1            |     result = block.nodelist.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
app_1            |     bit = self.render_node(node, context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
app_1            |     return node.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 150, in render
app_1            |     return template.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 148, in render
app_1            |     return self._render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 88, in instrumented_test_render
app_1            |     return self.nodelist.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render
app_1            |     bit = self.render_node(node, context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 80, in render_node
app_1            |     return node.render(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 201, in render
app_1            |     nodelist.append(node.render(context))
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 525, in render
app_1            |     six.iteritems(self.extra_context))
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 524, in <genexpr>
app_1            |     values = dict((key, val.resolve(context)) for key, val in
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 596, in resolve
app_1            |     obj = self.var.resolve(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 734, in resolve
app_1            |     value = self._resolve_lookup(context)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 788, in _resolve_lookup
app_1            |     current = current()
app_1            |   File "/opt/apps/amara/apps/activity/models.py", line 1247, in get_url
app_1            |     if self.type_obj.related_model is URLEdit:
app_1            |   File "/opt/apps/amara/apps/codefield/__init__.py", line 162, in get_code_obj
app_1            |     return self.value_to_code[self.slug_to_value[slug]]
app_1            | KeyError: 1007

**Comment by bendk** [comment] 2018-08-14 13:54
Here's how stats are calculated:

 - We split up the counts by day (midnight-midnight UTC)
 - "Yesterday" means the counts for the day before now
 - "Last Week" means the counts starting with the day before now and going 6 days before that.
 - We cache the stats per-day, since they are somewhat expensive to compute, we're planning on putting them on multiple pages, and I don't think we have plans to display the "today" count, which is the only one that would change.  If you want to make the "today" count update, then run `dev clear_cache`

**Comment by bendk** [comment] 2018-08-14 14:00
That traceback is caused by having an ENDORSE activity record in your DB.  I think that's just the result of dev testing and would happen with any branch.  You might need to run dev migrate, or maybe just start with a new DB to fix that issue.

**Comment by bendk** [comment] 2018-08-24 20:48
Merging this to dev

**Comment by PCF-Testing** [comment] 2018-09-11 00:05
This has been deployed a while ago.

**Closed by PCF-Testing** 2018-09-11 00:05 UTC
