### ISSUE TITLE
Subtitle timing overlap

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2588] opened 2016-06-17 12:45 UTC
Reported in FD ticket #85606.

Problem: 

1) Subtitles uploaded from a file can have overlapping subtitles (i.e. subtitle[i].start_time < subtitle[i-1].end_time). The import procedure does not detect and/or correct such issues.

2) When these subtitles are later edited and saved in the subtitle editor, the overlaps are not detected and corrected.

Examples:
http://www.amara.org/en/videos/v59Kt7olvLSy/en/1254992/?tab=revisions&revisions_per_page=160&page=1
Last good version: 141
In version 142 (uploaded): timing overlap at 
00:00:20.066 and speaking,
00:03:42.959 but the second language is something<br>I like to call "Woman in a Meeting,"
00:04:08.417 You put that into a woman<br>in a meeting, and it comes out,
00:08:28.447 Like sexism in laundry commercials.
00:08:40.583 if a woman doesn't put<br>a smiley face in an email,
00:08:48.792 If a woman doesn't put<br>an exclamation mark
00:07:52.727 "Yes, I've done this,<br>I'm a woman, this has happened."

http://www.amara.org/en/videos/i99cW0Xqgxcj/en
Last good version: 36
In version 37 (uploaded): timing overlap at
00:11:15.375 he would not have been<br>a professional baseball player.

More examples are available in the FD ticket.

**Comment by bendk** [comment] 2016-06-22 13:44
What's the correct behavior here?  As far as I know, overlapping subtitles are allowed by the DFXP and VTT specs.  So if someone uploads a file that contains them, I think we should do our best to work with them.  I don't think changing the timings when the file is uploaded or when the subtitles are saved is correct.

I think it's an open question what to do if those subtitles are actually edited in the editor.

**Comment by PCF-Testing** [comment] 2016-06-23 09:13
I believe the expected behavior is to highlight the overlapping subtitles in the editor: display a general error message in the progression panel, "Some of the subtitles overlap each other" (similarly  to "Subtitles cannot be blank" error message). Also, each troublesome subtitle should have an exclamation mark in the cell, the bad (overlapping time) highlighted in red in the flyover info tray, and the comment should say "This subtitle overlaps with the adjacent subtitle. Please check and correct start and end times."

When the start (or end) time is moved at the place of overlapping, both timestamps should change.

Does this make sense?

**Comment by bendk** [comment] 2016-06-23 13:46
That seems reasonable to me.  Do we have a ticket already for that issue?

**Comment by PCF-Testing** [comment] 2016-06-24 01:06
I have found only this one: https://github.com/pculture/unisubs/issues/813

**Comment by PCF-Testing** [comment] 2016-11-02 19:20
Still a nuisance: https://pculture.freshdesk.com/helpdesk/tickets/89100

**Comment by VeronicaPCF** [comment] 2017-02-10 11:49
**update from Krystian TED:** 
multiple other examples of overlap also found in revision 35 of these Portuguese subtitles: http://amara.org/en/videos/97kwlbNk4wDU/pt/1596998/4710615/ (e.g. at 00:04.999, 11.999 etc.).

I also found an instance of subtitle timing overlap: http://amara.org/en/videos/97kwlbNk4wDU/mn/1764308/4935617/. See Revision 18 of these subtitles, time: 02:08.214 (109 ms of overlap). I believe this was supposed to be resolved in June 2016 (see ticket #89100). The subtitles were created in the editor (no revision was uploaded from an external source).

**Any news on when/if this will be fixed? 
Thank you!
Veronica**

**Comment by PCF-Testing** [comment] 2017-02-10 13:11
The problem with the Portuguese subtitles was introduced in Revision 34. Version 33 is still good:
http://amara.org/en/videos/diffing/4710535/4710161/

**Comment by bendk** [comment] 2017-02-10 14:54
Does anyone have a way to reproduce this from the editor?  I'm still not sure how this could happen.

If you upload subtitles via the editor, what does the revision source say?  Does it still say "Subtitle Editor"?  If so, then maybe that's what's going on, also we should probably change that behavior.

**Comment by PCF-Testing** [comment] 2017-02-10 15:37
> If you upload subtitles via the editor, what does the revision source say? Does it still say "Subtitle Editor"?

Yes.

> Does anyone have a way to reproduce this from the editor?

Not with the use of regular upload and/or editing. There must be some other specific factor at play.

**Comment by bendk** [comment] 2017-02-10 16:02
I kind of think we've figured it out, can we contact the users and ask if they uploaded the subtitles?

I made #2754 for that issue.

**Comment by kslottow** [comment] 2017-02-25 04:33
@bendk is it correct that @VeronicaPCF should check with the user if they uploaded the subtitles for https://pculture.freshdesk.com/helpdesk/tickets/89100 , and that they should check and see if they're still experiencing the problem now?  (may have been fixed by #2754)

Based on one of Veronica's examples, though, overlap occurs sometimes when no revision has been uploaded. @PCF-Testing Does this mean there's another bug somewhere?

> revision 35 of these Portuguese subtitles (problem introduced in revision 34): http://amara.org/en/videos/97kwlbNk4wDU/pt/1596998/4710615/ (e.g. at 00:04.999, 11.999 etc.).

> http://amara.org/en/videos/97kwlbNk4wDU/mn/1764308/4935617/. See Revision 18 of these subtitles, time: 02:08.214 (109 ms of overlap). I believe this was supposed to be resolved in June 2016 (see ticket #89100). The subtitles were created in the editor (no revision was uploaded from an external source).

I made #2772 for how to handle/notify translators of overlapping subtitles when they appear in the editor

**Comment by PCF-Testing** [comment] 2017-02-25 09:01
> Based on one of Veronica's examples, though, overlap occurs sometimes when no revision has been uploaded.

There is no evidence for this because the versions that were uploaded through the subtitle editor were labeled as created in the subtitle editor and not uploaded. @bendk and I believe the first broken version in the sequence was uploaded.

**Comment by kslottow** [comment] 2017-03-13 13:04
So is it correct that we can't really figure out what happened in FD ticket #85606 because we didn't label versions as uploaded before (#2754 now we can)?  

Or is there more work to be done on this ticket that is not encompassed by #2754 and #2772 ?

**Comment by bendk** [comment] 2017-03-13 15:20
I think all of that is correct.

**Closed** 2017-04-10 07:30 UTC
Labels: client request
