### ISSUE TITLE
Style for subtitle visibility field

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3354] opened 2018-08-17 16:12 UTC
For subtitle visibility field on General Settings page.

- dependency switch, it should work just like a dependency checkbox.  The switch values should be "Public" and "Private"
- Above each switch should be a label, like in https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b7573cc6617eb79201d8357
- Below should be help text that explains the current setting value

Here's an example comp, but note the labels should be above the switches, not to the left of them. 
 https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b50c9f53231fa207b07c943)

The overall layout should be something like this:

```
Subtitle visibility
Completed               Drafts
[  o]Public             [o   ]Private
Completed subtitles are visible to everyone.  Draft subtitles
are visible only to your team
````

**Comment by bendk** [comment] 2018-08-21 19:35
Implemented this one and a bunch of other ones in the multiFields section of the styleguide.  This replaces the dependent checkboxes section, it's basically a more generalized version of that.

I also updated the switch styles to match the switches in that zepplin comp.  One thing to test is that the old switches still work.  As far as I know, the only ones are the follow switches on the  video/subtitles pages.

**Comment by PCF-Testing** [comment] 2018-08-23 14:34
The "filled" switch ([o   ]) looks and feels like a switch in ON position, as opposed to the grayed out [   o] switch. 

For subtitle visibility, ON logically means "Public" and OFF means 'Private". So I think "Private" and "Public" on the screenshot below should be the other way around:

![screenshot from 2018-08-23 07 21 33](https://user-images.githubusercontent.com/288455/44531531-dc431a80-a6a5-11e8-89af-f4b8f55a7d74.png)

P.S. I don't see any ticket for assignment time limits, but those fields happily accept 0 and negative values which they shouldn't.

**Comment by bendk** [comment] 2018-08-24 18:01
The first issue was just with the labels.  I fixed those.

The assignment time limit part of that styleguide page was just about how to present it.  Let's test 0/negative times when we implement the actual settings page.

**Comment by PCF-Testing** [comment] 2018-08-29 13:02
@bendk: The text in inline switches seems to be off center, the bottom part is below the lower edge. Not sure if it has been caused by the latest changes:

![screenshot from 2018-08-29 06 00 23](https://user-images.githubusercontent.com/288455/44789263-fae75c80-ab50-11e8-8fec-a8a1ab51f381.png)

![screenshot from 2018-08-29 06 00 42](https://user-images.githubusercontent.com/288455/44789280-08044b80-ab51-11e8-89d0-ac8029097291.png)

**Comment by bendk** [comment] 2018-08-29 15:27
Switch positioning should be fixed now.

**Comment by PCF-Testing** [comment] 2018-08-30 08:09
Great, thanks!

**Comment by PCF-Testing** [comment] 2018-09-11 00:11
Deployed.

**Closed by PCF-Testing** 2018-09-11 00:11 UTC
