### ISSUE TITLE
Errors viewing original during translation and downloading subtitles after changing the original track's language

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2415] opened 2015-11-23 14:36 UTC
Case was a French video that had been captioned by mistake in the English track. Then, the track's language had been set to French, and the video's original language to French, but the last revision was still an English revision, see #18 in http://amara.org/en/admin/subtitles/subtitlelanguage/1159677/

Upon starting a translation, the original language sidebar was blank. Also, trying to download the (now French) subtitles failed. After editing and saving a new revision (#19, now marked as a French revision) it worked.

Fix could be adding a new revision when the language setting is changed.

**Comment by PCF-Testing** [comment] 2016-09-12 23:34
The problem is is bit deeper than described in the ticket. The system currently works so that it is not enough to rename just SubtitleLanguage - you also need to change the language on all the related SubtitleVersions. Otherwise, in your example users would hit an error while trying to add English subtitles, because on attempt to save subtitles, the system would find that English version #1, #2 etc. already exist and having multiple instances of English v.1 for the same video is not allowed.

We should definitely address this issue at some point, but  this goes beyond the scope of this ticket. Marking as closed for now.

**Closed by PCF-Testing** 2016-09-12 23:34 UTC
