### ISSUE TITLE
Experimental editor: info tray not populated with data

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3488] opened 2018-10-25 15:17 UTC
This was observed on experimental-editor branch only. Does not happen in the experimental editor on dev (/?experimental url).

If you click on a subtitle cell in the typing panel or drag the boundary between subtitle balloons, the info trays for the matching subtitles do not get populated with the correct data:
![screenshot from 2018-10-25 08 17 28](https://user-images.githubusercontent.com/288455/47511158-75211e00-d82e-11e8-8477-1a2cf7971847.png)

**Comment by bendk** [comment] 2018-10-29 13:52
This is working for me, can you give me more detailed steps to reproduce?

**Comment by bendk** [comment] 2018-10-30 15:11
Should be fixed now.

**Comment by PCF-Testing** [comment] 2018-10-31 10:05
Verified the fix.

**Comment by bendk** [comment] 2018-10-31 14:59
I don't think we need a PR for this one, since we're going to review the experimental editor code all at once when we merge it into dev.  I made another issue for deploying the new experimental editor code.  I think we can close this one.

**Closed by bendk** 2018-10-31 14:59 UTC
Labels: bug, new editor
