### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 105: ordinal not in range(128)

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3020] opened 2017-11-13 15:02 UTC
https://sentry.io/pculture/unisubs/issues/403860126/

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 105: ordinal not in range(128)
(9 additional frame(s) were not displayed)
...
  File "videos/feed_parser/importer.py", line 101, in _create_video
    self.team)
  File "videos/models.py", line 724, in add
    video, video_url = cls._get_video_for_add(url, user, team)
  File "videos/models.py", line 773, in _get_video_for_add
    incomplete = video.set_values(vt, video_url, user, team)
  File "videos/models.py", line 780, in set_values
    incomplete = video_type.set_values(self, user, team, video_url)
  File "videos/types/htmlfive.py", line 87, in set_values
    cmd = """avprobe -v error -show_format -show_streams "{}" 2>&1 """.format(self.url)

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 105: ordinal not in range(128)
```

**Comment by PCF-Testing** [comment] 2017-11-18 11:53
@bendk: @syl22-00: do you have an idea how this bug can be reproduced?

**Comment by bendk** [comment] 2017-11-20 14:10
It looks to me like it could happen when you add an htmlfive video URL, with a non-ascii character in the URL (not sure exactly how that happens), then we try to run ffmpeg on it to determine the duration.

I'm not sure if that's possible to reproduce though.

**Comment by syl22-00** [comment] 2017-11-20 14:23
@PCF-Testing @bendk Right, this issue is when the url of an mp4 file contains unicode non-ascii characters, for instance 2018. There is also a test in the branch to make sure the fix works

**Comment by PCF-Testing** [comment] 2017-11-21 11:21
Still seeing the error locally on branch gh-unisubs-3020.

Tested with the video http://www.engagemedia.org/Members/DVB/videos/doh-pyay-doh-myay/@@download/video_file/Doh Pyay Doh Myay_ ‘Like a seagull searching for food in the sea’ .mp4, which is from EngageMedia feed.

Error (on submitting the video through /video/create):
app_1      | ERROR 2017-11-21 05:18:10,708 unhandled_error 'ascii' codec can't encode character u'\u2018' in position 105: ordinal not in range(128)
app_1      | Traceback (most recent call last):
app_1      |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1      |     response = callback(request, *callback_args, **callback_kwargs)
app_1      |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
app_1      |     return view_func(request, *args, **kwargs)
app_1      |   File "/opt/apps/amara/apps/videos/views.py", line 239, in create
app_1      |     if video_form.is_valid():
app_1      |   File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 124, in is_valid
app_1      |     return self.is_bound and not bool(self.errors)
app_1      |   File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 115, in _get_errors
app_1      |     self.full_clean()
app_1      |   File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 271, in full_clean
app_1      |     self._clean_form()
app_1      |   File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 299, in _clean_form
app_1      |     self.cleaned_data = self.clean()
app_1      |   File "/opt/apps/amara/apps/videos/forms.py", line 246, in clean
app_1      |     self.cleaned_data['video_url'], self.user)
app_1      |   File "/opt/apps/amara/apps/videos/models.py", line 732, in add
app_1      |     video_cache.invalidate_cache(video.video_id)
app_1      |   File "/opt/apps/amara/apps/widget/video_cache.py", line 98, in invalidate_cache
app_1      |     cache.delete(_video_id_key(url.url))
app_1      |   File "/opt/apps/amara/apps/widget/video_cache.py", line 121, in _video_id_key
app_1      |     return 'video_id_{0}'.format(hashlib.sha1(video_url).hexdigest())
app_1      | UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 105: ordinal not in range(128)
app_1      | INFO 2017-11-21 05:18:10,802 access POST /videos/create/ 500 (0.985s)

**Comment by syl22-00** [comment] 2017-11-21 12:33
@PCF-Testing There was a similar issue in the caching code, I fixed and pushed it.

**Comment by PCF-Testing** [comment] 2017-11-22 09:35
2 unit tests are broken on the branch:

======================================================================
FAIL: test_fetch_subs (externalsites.tests.test_subfetch.SubFetchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_subfetch.py", line 145, in test_fetch_subs
    mock.call(self.account.oauth_refresh_token))
AssertionError: None != call('refresh-token')
-------------------- >> begin captured logging << --------------------
externalsites.subfetch: WARNING: fetch_subs() no available credentials.
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_fetch_subs_handles_bcp47_codes (externalsites.tests.test_subfetch.SubFetchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_subfetch.py", line 200, in test_fetch_subs_handles_bcp47_codes
    mock.call('test-access-token', 'caption-1'))
AssertionError: None != call('test-access-token', 'caption-1')
-------------------- >> begin captured logging << --------------------
externalsites.subfetch: WARNING: fetch_subs() no available credentials.
--------------------- >> end captured logging << ---------------------

and the branch does not pull metadata from the public Vimeo videos.

**Comment by syl22-00** [comment] 2017-11-22 16:14
So I made the fix also for the feeds. I am a little bit surprised we did not have this earlier, hopefully I am not doing anything wrong.
Broken tests are from another branch.

**Comment by PCF-Testing** [comment] 2017-11-23 15:11
When I try submitting the same URL now, it gets escaped and the resulting URL is not playable in the embedder or editor: http%3A//www.engagemedia.org/Members/DVB/videos/doh-pyay-doh-myay/%40%40download/video_file/Doh%20Pyay%20Doh%20Myay_%20%E2%80%98Like%20a%20seagull%20searching%20for%20food%20in%20the%20sea%E2%80%99%20.mp4

Happens both in the public area and in a team.

**Comment by syl22-00** [comment] 2017-12-14 21:11
So I made a new implementation in gh-unisubs-3020-redo
Now URLs of direct files (FLV, MP3, HTML5) are stored percent-encoded.
For existing urls to still work in the embedder and editor, it is necessary to run:

```
./bin/dev manage encode_urls
```
This can not be undone, so better run it first on non-important database.

**Comment by PCF-Testing** [comment] 2017-12-15 15:48
Got an exception when adding the troublesome URL via API:

AttributeError at /api/videos/
'NoneType' object has no attribute 'items'
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/api/videos/
Django Version:	1.4.22
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'items'
Exception Location:	/usr/local/lib/python2.7/dist-packages/rest_framework/utils/serializer_helpers.py in as_form_field, line 99
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  134.                     response = response.render()
File "/usr/local/lib/python2.7/dist-packages/django/template/response.py" in render
  104.             self._set_content(self.rendered_content)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/response.py" in rendered_content
  60.         ret = renderer.render(self.data, media_type, context)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py" in render
  669.         context = self.get_context(data, accepted_media_type, renderer_context)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py" in get_context
  646.             'post_form': self.get_rendered_html_form(data, view, 'POST', request),
File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py" in get_rendered_html_form
  513.                     [('template', 'rest_framework/api_form.html')]
File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py" in render
  367.         return template.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  140.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  186.                         nodelist.append(node.render(context))
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  282.                 return nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  1107.                     return func(*resolved_args, **resolved_kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/templatetags/rest_framework.py" in render_field
  31.     return renderer.render_field(field, style)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py" in render_field
  325.         field = field.as_form_field()
File "/usr/local/lib/python2.7/dist-packages/rest_framework/utils/serializer_helpers.py" in as_form_field
  99.         for key, value in self.value.items():

Exception Type: AttributeError at /api/videos/
Exception Value: 'NoneType' object has no attribute 'items'

The encoding procedure seems to work, but the solution used does seem a bit risky and scary, so I feel that in this case the medicine might be worse than the disease itself.

**Comment by syl22-00** [comment] 2017-12-15 20:57
@PCF-Testing It actually does work for me, can you send me the exact URL you are using? Does the same call with another html5 url works right?

**Comment by PCF-Testing** [comment] 2017-12-16 10:13
@syl22-00: it is the same video this ticket is dedicated to - http://www.engagemedia.org/Members/DVB/videos/doh-pyay-doh-myay/@@download/video_file/Doh Pyay Doh Myay_ ‘Like a seagull searching for food in the sea’ .mp4. The API call payload had just two parameters - the video URL and the destination team. With other videos - MP4 or YouTube - the same API call works without a hitch.

**Comment by syl22-00** [comment] 2017-12-19 21:16
@PCF-Testing 
So, the reason why this URL did not work was because spaces are not valid for IRI, while ASCII and Unicode characters are valid. So it is fine to reject this URL.

Meanwhile, there was an issue in the API when there was errors submitting urls with unicode characters, the error message failed being created. This is now fixed.

I also added a fix for an issue we had not detected: we allow URLs up to 2048 characters but the API used the default limit of 200. I changed that to share the same 2048 limit.

Another change I made was that when added a url to an existing video, the url was considered a charfield, meaning any string was accepted.

Those fixes are in the same branch.

**Comment by PCF-Testing** [comment] 2017-12-21 16:07
Verified.

**Comment by PCF-Testing** [comment] 2018-01-03 20:32
Deployed.

**Closed by PCF-Testing** 2018-01-03 20:32 UTC
Labels: fix-it

**Comment by syl22-00** [comment] 2018-01-08 21:16
@PCF-Testing just to be sure: the management command needs to be run in order to have existing URLs with unicode characters to still work.

**Comment by PCF-Testing** [comment] 2018-01-08 22:27
@syl22-00: thanks, @bendk ran this command against the production last week, so this should be all set.
