### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3408] opened 2018-09-14 14:04 UTC
https://sentry.io/pculture/unisubs-staging/issues/686403005/

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
(30 additional frame(s) were not displayed)
...
  File "teams/new_views.py", line 1122, in settings_basic
    'settings_tab': 'general',
  File "ui/templatetags/forms.py", line 61, in render_field_filter_version
    return render_field(field)
  File "ui/templatetags/forms.py", line 44, in render_field
    'label': calc_label(field, reverse_required),
  File "ui/templatetags/forms.py", line 111, in calc_label
    return label_with_optional(field.label)
  File "ui/templatetags/forms.py", line 125, in label_with_optional
    unicode(label), _('(optional)'))

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
```

**Comment by PCF-Testing** [comment] 2018-09-15 12:32
Works well now.

**Comment by PCF-Testing** [comment] 2018-09-18 00:41
Marking as closed because it is just a regression issue.

**Closed by PCF-Testing** 2018-09-18 00:41 UTC
