### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3041] opened 2017-12-04 14:22 UTC
https://sentry.io/pculture/unisubs/issues/412939281/

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)
(13 additional frame(s) were not displayed)
...
  File "socialauth/views.py", line 156, in openid_login
    return begin(request, confirmed=confirmed)
  File "openid_consumer/views.py", line 105, in begin
    auth_request = consumer.begin(user_url)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)
```

**Comment by syl22-00** [comment] 2017-12-04 14:24
Seems like another instance of #3020

**Comment by kslottow** [comment] 2017-12-18 21:04
@syl22-00 I saw that you self-assigned this, but might be better to share any insights you have or the process you would use for Ben or Amelia to do later, and put it in the backlog?

**Comment by asabine** [comment] 2018-01-08 20:56
the python-openid library specifies that the user_url parameter of the Consumer object is expected as type unicode; it gets converted into unicode during the discovery process, so first we'll try to convert to unicode from ascii, and if that throws a UnicodeDecodeError, we decode from utf-8 instead. the error was caused by a user_url string (for python2 represented in bytes iirc) being converted to unicode with the default assumed encoding of the source string set to ascii.

**Comment by asabine** [comment] 2018-01-08 20:57
(this was a separate issue from 3020 in general, which was an encode error, not a decode error)

**Comment by PCF-Testing** [comment] 2018-01-18 14:21
@asabine: can you think of a good way to reproduce this issue? Is it also about a url with a utf char in it?

**Comment by asabine** [comment] 2018-01-31 15:16
@PCF-Testing yes, 0xe1 is just the letter á and the issue is caused by the openid user_url having a non-ascii unicode symbol

**Comment by PCF-Testing** [comment] 2018-02-08 12:19
@asabine: I am not sure how to reproduce this issue. I have changed the name in the test FB account to include this non-ascii character - https://www.facebook.com/pat.culture, but using it to sign up / sign in does not cause this error. Instead, I am getting a bunch of different errors:

app_1            | ERROR 2018-02-08 05:51:16,904 thirdpartyaccounts.views facebook_login
app_1            | ERROR 2018-02-08 05:51:16,904 thirdpartyaccounts.views {'csrftoken': _elided_, 'fbsr_255603057797860': _elided_, 'fbm_255603057797860': 'base_domain=.unisubs.example.com', 'unisub-user-uuid': _elided_, 'language': 'en'}
app_1            | ERROR 2018-02-08 05:51:16,904 thirdpartyaccounts.views csrftoken
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views _elided_
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views fbsr_255603057797860
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views _elided_
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views fbm_255603057797860
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views base_domain=.unisubs.example.com
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views unisub-user-uuid
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views _elided_
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views language
app_1            | ERROR 2018-02-08 05:51:16,905 thirdpartyaccounts.views en
app_1            | ERROR 2018-02-08 05:51:16,984 thirdpartyaccounts.views data
app_1            | ERROR 2018-02-08 05:51:16,984 thirdpartyaccounts.views {u'issued_at': 1518090676, u'code': _elided_, u'user_id': u'1911155202289756', u'algorithm': u'HMAC-SHA256'}
app_1            | INFO 2018-02-08 05:51:18,015 access GET /auth/facebook_login_confirm/pculture.qa@gmail.com/ 302 (1.112s)
app_1            | INFO 2018-02-08 05:51:18,068 access GET /auth/confirm_create/facebook/pculture.qa@gmail.com/ 200 (0.051s)
app_1            | INFO 2018-02-08 05:51:18,103 access GET /media/css/hands_home.css 200 (0.004s)
app_1            | INFO 2018-02-08 05:51:18,108 access GET /media/js/site.js 200 (0.005s)
app_1            | INFO 2018-02-08 05:51:18,111 access GET /media/js/hands_home.js 200 (0.002s)
app_1            | INFO 2018-02-08 05:51:18,114 access GET /media/jsi18catalog/en.js 200 (0.003s)
app_1            | INFO 2018-02-08 05:51:18,117 access GET /profiles/router/api/ 200 (0.001s)
app_1            | INFO 2018-02-08 05:51:18,119 access GET /embedder-iframe/ 200 (0.002s)
app_1            | INFO 2018-02-08 05:51:18,122 access GET /media/js/login.js 200 (0.002s)
app_1            | INFO 2018-02-08 05:51:18,165 access GET /media/jslanguagedata/en.js 200 (0.066s)
app_1            | ERROR 2018-02-08 05:51:20,867 thirdpartyaccounts.views facebook_login
app_1            | ERROR 2018-02-08 05:51:20,867 thirdpartyaccounts.views {'csrftoken': _elided_, 'fbsr_255603057797860': _elided_, 'fbm_255603057797860': 'base_domain=.unisubs.example.com', 'unisub-user-uuid': _elided_, 'language': 'en'}
app_1            | ERROR 2018-02-08 05:51:20,867 thirdpartyaccounts.views csrftoken
app_1            | ERROR 2018-02-08 05:51:20,867 thirdpartyaccounts.views _elided_
app_1            | ERROR 2018-02-08 05:51:20,867 thirdpartyaccounts.views fbsr_255603057797860
app_1            | ERROR 2018-02-08 05:51:20,867 thirdpartyaccounts.views _elided_
app_1            | ERROR 2018-02-08 05:51:20,867 thirdpartyaccounts.views fbm_255603057797860
app_1            | ERROR 2018-02-08 05:51:20,868 thirdpartyaccounts.views base_domain=.unisubs.example.com
app_1            | ERROR 2018-02-08 05:51:20,868 thirdpartyaccounts.views unisub-user-uuid
app_1            | ERROR 2018-02-08 05:51:20,868 thirdpartyaccounts.views _elided_
app_1            | ERROR 2018-02-08 05:51:20,868 thirdpartyaccounts.views language
app_1            | ERROR 2018-02-08 05:51:20,868 thirdpartyaccounts.views en
app_1            | ERROR 2018-02-08 05:51:20,868 thirdpartyaccounts.views data
app_1            | ERROR 2018-02-08 05:51:20,868 thirdpartyaccounts.views {u'issued_at': 1518090678, u'code': _elided_, u'user_id': u'1911155202289756', u'algorithm': u'HMAC-SHA256'}
app_1            | INFO 2018-02-08 05:51:24,327 access POST /auth/confirm_create/facebook/pculture.qa@gmail.com/ 302 (3.513s)

Do you have any other idea how the original issue can be reproduced?

**Comment by asabine** [comment] 2018-02-08 18:26
@PCF-Testing i don't see a non-ascii character in that link; but those errors aren't really errors it seems, in the facebook_login code there's a bunch of logger.error() calls that print out this information for no reason? i'm guessing it was used during development at some point but i'm going to remove those since we really shouldn't be logging this information in the first place

**Comment by PCF-Testing** [comment] 2018-02-09 09:56
Is there a way to produce a user_url with a non-ascii character in it? Google and Twitter only use Latin characters in the usernames, and I have never seen an FB profile link with a non-Latin character.

**Comment by asabine** [comment] 2018-02-09 14:33
the easiest way i can think is to use a web proxy and edit and send the request manually during the process? i'm not sure what we can do to include a non-ascii character on other websites, since i'm not sure which sites supporting openid allow that

**Comment by PCF-Testing** [comment] 2018-02-09 14:40
What should such request look like?

**Comment by asabine** [comment] 2018-02-09 14:41
not sure off the top of my head what the entire request would look like; i know in both owasp zap and burp proxy you can change individual parameters of a request in progress, and in that case i'd just change the user_url parameter to use an invalid character

**Comment by PCF-Testing** [comment] 2018-02-12 12:31
Verified.

**Comment by PCF-Testing** [comment] 2018-03-07 08:47
Deployed.

**Closed by PCF-Testing** 2018-03-07 08:47 UTC
Labels: fix-it
