### ISSUE TITLE
Sync History should display to team admins

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#1291] opened 2014-03-07 17:54 UTC
Currently sync history only displays to Amara users with superuser status. It should display to team admin's so that they can more directly help assess syncing issues and re-sync if needed, without contacting Amara support.

**Comment by bendk** [comment] 2015-01-06 19:43
Are we going to allow team admins access to the resync button?

**Comment by darren-bridenbeck** [comment] 2015-01-06 19:59
Now that we have #1858 being worked on, it seems like less important to
give admins access to the resync button. Nonetheless, giving them access to
it could help empower admins to troubleshoot their own issues without
needing to submit a ticket. What kind of drawbacks would there be from
giving admins access?

**Comment by bendk** [comment] 2015-01-06 20:05
I don't think it would be too bad.  If an admin spammed the button it would generate some extra work for us.  But it seems useful overall and would reduce our help request volume.

**Comment by syl22-00** [comment] 2015-04-20 12:14
In branch gh-1291, made tab and button accessible to:
* staff members
* video owners
* team admin and owners

**Comment by jdragojevic** [comment] 2015-04-22 10:27
Getting this error when trying to open the sync history tab of a team video

```
app_1 | ERROR 2015-04-22 05:26:35,936 base 12 140642447111936 Internal Server Error: /en/videos/qguHQNkZ3ADc/en-gb/349/
app_1 | Traceback (most recent call last):
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1 |     response = callback(request, *callback_args, **callback_kwargs)
app_1 |   File "/opt/apps/unisubs/apps/videos/decorators.py", line 42, in wrapper
app_1 |     return func(request, video, *args, **kwargs)
app_1 |   File "/opt/apps/unisubs/apps/videos/views.py", line 687, in language_subtitles
app_1 |     return render(request, template_name, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 44, in render
app_1 |     return HttpResponse(loader.render_to_string(*args, **kwargs),
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 176, in render_to_string
app_1 |     return t.render(context_instance)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
app_1 |     return self._render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 63, in instrumented_test_render
app_1 |     return self.nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
app_1 |     return compiled_parent._render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 63, in instrumented_test_render
app_1 |     return self.nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
app_1 |     return compiled_parent._render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 63, in instrumented_test_render
app_1 |     return self.nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
app_1 |     result = block.nodelist.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 823, in render
app_1 |     bit = self.render_node(node, context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
app_1 |     return node.render(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 275, in render
app_1 |     match = condition.eval(context)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 825, in eval
app_1 |     return self.value.resolve(context, ignore_failures=True)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 599, in resolve
app_1 |     new_obj = func(obj, *arg_vals)
app_1 |   File "/opt/apps/unisubs/apps/videos/templatetags/videos_tags.py", line 56, in can_user_resync
app_1 |     return permissions.can_user_resync(video, user)
app_1 |   File "/opt/apps/unisubs/apps/videos/permissions.py", line 41, in can_user_resync
app_1 |     return teams_permissions.can_resync(team_video, user)
app_1 |   File "/opt/apps/unisubs/apps/teams/permissions.py", line 751, in can_resync
app_1 |     role = get_role_for_target(user, team)
app_1 |   File "/opt/apps/unisubs/apps/teams/permissions.py", line 95, in get_role_for_target
app_1 |     member = get_member(user, team)
app_1 |   File "/opt/apps/unisubs/apps/teams/permissions.py", line 76, in get_member
app_1 |     return team.get_member(user)
app_1 | AttributeError: 'TeamVideo' object has no attribute 'get_member'
```

**Comment by jdragojevic** [comment] 2015-04-24 07:06
@syl22-00 As a team admin -  am able to see the Sync History tab on the video language, however if I click the ```Resync version X``` button on the page,

![image](https://cloud.githubusercontent.com/assets/299270/7314075/06db98a8-ea61-11e4-864f-e110ce060cf7.png)

 I am getting prompted to login as a site admin.

This is the page url: http://unisubs.example.com:8000/en/externalsites/resync/266/hr/

![image](https://cloud.githubusercontent.com/assets/299270/7314091/23cfa9f4-ea61-11e4-9ebe-6c3bcea16675.png)

**Comment by syl22-00** [comment] 2015-04-24 07:32
Sorry @jdragojevic , that should be fixed now

**Comment by jdragojevic** [comment] 2015-04-24 09:20
got this error trying to login access admin pages:


```
app_1 | ERROR 2015-04-24 04:18:15,662 base 1007 140708931417856 Internal Server Error: /en/admin/
app_1 | Traceback (most recent call last):
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1 |     response = callback(request, *callback_args, **callback_kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 213, in wrapper
app_1 |     return self.admin_view(view, cacheable)(*args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
app_1 |     response = view_func(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
app_1 |     response = view_func(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 196, in inner
app_1 |     return view(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
app_1 |     response = view_func(request, *args, **kwargs)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 338, in index
app_1 |     has_module_perms = user.has_module_perms(app_label)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 368, in has_module_perms
app_1 |     return _user_has_module_perms(self, app_label)
app_1 |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 215, in _user_has_module_perms
app_1 |     anon = user.is_anonymous()
app_1 | TypeError: 'bool' object is not callable
app_1 | [24/Apr/2015 04:18:15] "GET /en/admin/ HTTP/1.1" 500 202262

```

**Comment by jdragojevic** [comment] 2015-04-24 09:34
For the display of the sync tab for users (only related to youtube videos).  Currently we are allowing the submitter to see the sync tab.  That permission should actually be reserved for the video owner. 

For example - if I submit a video that is owned by Sylvain's youtube channel - I should not see the sync tab for languages.  And Sylvain should probably only see the Sync History tab if he has linked his account.  Basically the channel owner should control resyncing.

I think we can/should limit this ticket to the scope of team videos only - and make a new ticket for user accounts.   Maybe we'll want to add in some way to link users to the channel owners page and ask them to link an accout it it's not linked.

**Comment by jdragojevic** [comment] 2015-04-24 12:56
confirmed that with bed97e6db22b737 is_staff can see the Sync history page of user videos, but not the video submitter.

**Comment by jdragojevic** [comment] 2015-04-29 07:24
@syl22-00 I think the last thing we talked about doing here was adding some type of visual indicator to the Sync history page to let the admin know if they should expect this video to sync.

Currently on the urls page of a video - we have the synced badge to indicate if that particular URL is configured for syncing.
![image](https://cloud.githubusercontent.com/assets/299270/7386058/a3efc938-ee4f-11e4-99d4-e75deaa350d4.png)

When we get to they Sync History tab for the Video language - we show all urls that could potentially be synced.  So you see the Kaltura URL is listed in there, even though it's not configured, and an admin can click that all day.

![image](https://cloud.githubusercontent.com/assets/299270/7386069/d4ce8d14-ee4f-11e4-9a06-7244260fbfe0.png)

We should update the table display to indicate to the user what exactly is happening with each url:

1. Don't show the resync button if syncing isn't configured for that URL.
2. Under version for that entry show 'syncing not configured'
3. For urls that have syncing enabled, but no current history - show 'no sync history' in the version field.

Something like this:

![image](https://cloud.githubusercontent.com/assets/299270/7386178/28de217a-ee51-11e4-8d39-79e4c066051d.png)

**Comment by syl22-00** [comment] 2015-04-29 11:14
@jdragojevic that should be done now

**Comment by jdragojevic** [comment] 2015-04-29 18:07
@syl22-00, I think I was wrong about changing the version field value from 'None' to 'no syncing history'

Because in the case of a failure, then it will still say 'no syncing history' and have a failure entry in the history.  

So can you please change it back to None, in the case that there is no value.  Sorry.

![image](https://cloud.githubusercontent.com/assets/299270/7397833/4be31234-eeab-11e4-8205-833ca0d1fc2b.png)

**Comment by jdragojevic** [comment] 2015-05-04 08:41
deployed.

**Closed by jdragojevic** 2015-05-04 08:41 UTC
Labels: pri:  important, status 4 merged-to-staging
