### ISSUE TITLE
As a captioner, I want a wider clickable dragging area so I can easily drag subtitle endpoints.

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2638] opened 2016-09-27 18:20 UTC
Usually we do all the dragging of subtitle endpoints in the editing step (after syncing) - the dragging areas are very small and it's a hassle to navigate to the exact clickable areas.

I've noticed this personally, and it has been mentioned in the forum discussion on the new editor multiple times by different users, both around 3 years ago when the editor was originally released.
- Mike Ridgeway: from p.4 of the "New Editor Feedback" forum discussion, 3 years ago
  "And still, the narrow margin of error for grabbing a captions edge for syncing is making me take a very long time to make a small adjustment -- so much so that I am, again, returning to the legacy editor to do my work today.  The improvements are appreciated.  Hoping that soon the user experience in the new editor will be solidly superior to that of the legacy editor."
- Verone Black: (he demos this problem at 2:19 seconds in the following video) http://www.amara.org/fr/videos/xuNgGxPArFDM/info/test-us/

@nslottow Janet from PCF 3 years ago replied to these two saying a larger dragging area was "in staging," so maybe there is code in the pipeline somewhere already for this that just hasn't gone through the entire process.  Do you think we should ask Maggie or Ben if they're aware of a pre-existing issue?

![drag_new_editor](https://cloud.githubusercontent.com/assets/22455700/19562514/3ace6d18-96a2-11e6-88b2-a350356461db.png)

![drag_legacy_editor](https://cloud.githubusercontent.com/assets/22455700/19562434/e9ed26aa-96a1-11e6-8c7d-8f2b37d9e927.png)

Suggestion: While changing to UI may be helpful in the future, I think simply making the dragging area clickable from a larger area into the subtitle will make this step of the process (adjusting subtitle timing) significantly easier.  

Green area shows where I think we should be able to drag from.  Red areas refer to issue #1592 
![timeline_moves](https://cloud.githubusercontent.com/assets/22455700/19565890/1df7f428-96ae-11e6-998d-e79a1457f34f.png)

Repro steps:
1) Open a video with synced subtitles in the "review and complete" stage. Here is the one I used: http://staging.amara.org/en/subtitles/editor/YTPcMZ2JAzrN/en/
2) Hover over the endpoints of subtitles to see dragging area clickable width.

**Comment by kslottow** [comment] 2016-10-20 21:31
@nslottow There's one thing about Darren's issue #1592 that isn't covered here: the areas above and below the text drag the timeline instead of the subtitle, which seems like a separate issue from "being able to drag subtitle endpoints easily."  Thoughts?

**Comment by nslottow** [comment] 2016-10-20 21:35
I marked #1592 as a duplicate of this one because all of #1592, this issue #2638, and in my opinion #2671 are fixed by the same small change that I'm about to push.  I don't think there's any more work to be done to investigate or fix these 3 issues separately.

**Comment by nslottow** [comment] 2016-10-20 21:50
@PCF-Testing The fix for these drag area issues has been pushed to pculture/unisubs [branch gh-2638](/pculture/unisubs/tree/gh-2638).  It turned out to be a simple CSS fix.  Moving this into testing.

**Comment by PCF-Testing** [comment] 2016-10-21 15:30
Making a PR for this one.

**Comment by PCF-Testing** [comment] 2016-10-25 14:28
I'll close this one when it goes live and the release notes get posted.

**Comment by PCF-Testing** [comment] 2016-10-31 09:48
Deployed.

**Closed by PCF-Testing** 2016-10-31 09:48 UTC
Labels: new editor
